const data = [
    "It was a really good Monday for being a Saturday.",
    "Dolores wouldn't have eaten the meal if she had known what it actually was.",
    "Hang on, my kittens are scratching at the bathtub and they'll upset by the lack of biscuits.",
    "Normal activities took extraordinary amounts of concentration at high altitude.",
    "She had some amazing news to share but nobody to share it with.",
    "I’m working on a sweet potato farm.",
    "She advised him to come back at once.",
    "She thought there'd be sufficient time if she hid her watch.",
    "He had accidentally hacked into his company's server.",
    "That must be the tenth time I've been arrested for selling deep-fried cigars.",
    "She opened up her third bottle of wine of the night.",
    "There is no better feeling than staring at a wall with closed eyes.",
    "You can't compare apples and oranges, but what about bananas and plantains?",
    "I'm confused: when people ask me what's up, and I point, they groan.",
    "The ants enjoyed the barbecue more than the family.",
    "Thirty years later, she still thought it was okay to put the toilet paper roll under rather than over.",
    "She was only made the society president because she can whistle with her toes.",
    "He barked orders at his daughters but they just stared back with amusement.",
    "The sunblock was handed to the girl before practice, but the burned skin was proof she did not apply it.",
    "My biggest joy is roasting almonds while stalking prey.",
    "She moved forward only because she trusted that the ending she now was going through must be followed by a new beginning.",
    "The stench from the feedlot permeated the car despite having the air conditioning on recycled air.",
    "At that moment I was the most fearsome weasel in the entire swamp.",
    "The irony of the situation wasn't lost on anyone in the room.",
    "The delicious aroma from the kitchen was ruined by cigarette smoke.",
    "Homesickness became contagious in the younger campers cabin.",
    "Just because the water is red doesn't mean you can't drink it.",
    "He's in a boy band which doesn't make much sense for a snake.",
    "Never underestimate the willingness of the greedy to throw you under the bus.",
    "Dan took the deep dive down the rabbit hole.",
    "I checked to make sure that he was still alive.",
    "The pet shop stocks everything you need to keep your anaconda happy.",
    "The external scars tell only part of the story.",
    "No matter how beautiful the sunset, it saddened her knowing she was one day older.",
    "Please tell me you don't work in a morgue.",
    "He found the chocolate covered roaches quite tasty.",
    "He figured a few sticks of dynamite were easier than a fishing pole to catch fish.",
    "The beauty of the sunset was obscured by the industrial cranes.",
    "The skeleton had skeletons of his own in the closet.",
    "We debated the greater need for an umbrella, in sunshine for shade or in rain for dryness.",
    "Today we gathered moss for my uncle's wedding.",
    "It caught him off guard that space smelled of seared steak.",
    "The police officer cautiously approached the black sedan.",
    "The fish listened intently to what the frogs had to say.",
    "Nudist colonies shun fig-leaf couture.",
    "Behind the window was a reflection that only instilled fear.",
    "She had a difficult time owning up to her own crazy self.",
    "After exploring the abandoned building, he started to believe in ghosts.",
    "Kevin embraced his ability to be at the wrong place at the wrong time.",
    "Acres of almond trees lined the interstate highway which complimented the crazy driving nuts.",
];

export default data;
